# Generated by Django 4.2 on 2024-01-29 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_product_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
