# Generated by Django 4.2 on 2024-01-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
